version: '3.8'

services:
  vue_app: # o nome do serviço
    image: node # a imagem Docker a ser usada para este serviço
    volumes: # monta volumes
      - ./:/app
    working_dir: /app
    command: bash -c "npm install && npm run serve"
    ports: # as portas que serão expostas
      - '8080:8080'